apiVersion: v1
kind: Secret
metadata:
  name: repo-mycluster
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: mycluster-repo
  url: https://example.com/clusters/mycluster.git
  type: git
  username: 'terraform'
  password: 'secretkey'
